Brightspace/outcomes-level-of-achievement-ui

bower.json
components.html
d2l-outcomes-level-of-achievements.html
d2l-outcomes-loa-demonstration-level.html
demo/d2l-outcomes-level-of-achievements.html
demo/d2l-squishy-button-selector.html
squishy-button-selector/d2l-squishy-button-selector.html
squishy-button-selector/d2l-squishy-button.html
test/components/d2l-squishy-button-selector.js

Now it shows the appropriate levels of achievement and allows you to select them

Hypermedia integration

---

d2l-outcomes-level-of-achievements.html
d2l-outcomes-loa-demonstration-level.html
squishy-button-selector/d2l-squishy-button.html

Use a property since getting the css var to bubble to the host wasn't working

make colors work from hm

---

d2l-outcomes-level-of-achievements.html

@jopnick insists this is better (haven't updated API yet)

switch rel domain

---

d2l-outcomes-level-of-achievements.html
squishy-button-selector/d2l-squishy-button-selector.html
squishy-button-selector/d2l-squishy-button.html
test/components/d2l-squishy-button-selector.js

Needs: https://git.dev.d2l/projects/CORE/repos/le/pull-requests/12657/overview

Make the ui work with the deselect action

---

squishy-button-selector/d2l-squishy-button-selector.html
squishy-button-selector/d2l-squishy-button.html

This brings the selector closer to the design of other menu items and gives a visual cue when deselecting from the keyboard

no borders on focus

---

d2l-outcomes-loa-demonstration-level.html

the buttons should always have bold text

---

d2l-outcomes-level-of-achievements.html

Can't test out locally atm, but seems pretty trivial

9rem (180px) max on button width

---

squishy-button-selector/d2l-squishy-button-selector.html

Fixing an error showing up in IE console

DE31848 - IE is showing console errors for the missing :'s

---

demo/d2l-squishy-button-selector.html
squishy-button-selector/d2l-squishy-button-selector.html
squishy-button-selector/d2l-squishy-button.html

Got a little carried away. Was going to PR things to your branch, but then figured I should clean a couple things up in master first.

Simplify structures

---

.eslintrc.json
build/lang/ar.js
build/lang/de.js
build/lang/en.js
build/lang/es.js
build/lang/fr.js
build/lang/ja.js
build/lang/ko.js
build/lang/nl.js
build/lang/pt.js
build/lang/sv.js
build/lang/tr.js
build/lang/zh-tw.js
build/lang/zh.js
index.html
langtools/build.js
langtools/build.template
langtools/config.json
langtools/copy.js
package.json

For copying/building lang term files

Add lang tools

---

squishy-button-selector/d2l-squishy-button-selector.js
squishy-button-selector/d2l-squishy-button.js

Change: Move background-color from selector to button

DE34000 - Remove whitespace on display for outcomes for paper assignments

---

d2l-outcomes-level-of-achievements.js
demo/d2l-outcomes-level-of-achievements.html

Also, it seems that `demo/d2l-outcomes-level-of-achievements.html` is broken, so removed imports that cause the issue

DE34001: Do not recalculate suggested level when manually selected level

---

package.json
squishy-button-selector/d2l-squishy-button-selector.js
squishy-button-selector/d2l-squishy-button.js

Update d2l-colors/typography to use BS UI core

Fix font issues from lit conversion

---

d2l-outcomes-coa-eval-override.js
d2l-outcomes-level-of-achievements.js
package.json

...and throw an event for consistent-eval to handle instead.

Disable Autosave for coa-eval-override

---

package-lock.json
package.json

Bump version to 3.0.18

---

README.md
package.json

This will run the various linters in fix mode to help get rid of pedantic issues.

Add format command to npm scripts

---

d2l-outcomes-level-of-achievements.js

https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fdefect%2F512326677084

apply d2l-body-small on suggested level text

---

localize-mixin.js
package-lock.json
package.json

Relative path was incorrect. Accidently had it fixed locally and forgot to include the change 😞.

US125911 - Fix languages

---

package.json
test/.eslintrc.json

Corrects link to repo as well.

Clean-up unneeded stuff in package.json

---

README.md
package.json

This is better matches our "standard" README layout.

Update README to better reflect available commands

---

package-lock.json
package.json
squishy-button-selector/d2l-squishy-button.js

All the remove dependencies seem to be hold overs from when this component was polymer. The only code references weren't used.

fix: remove unused dependencies

---

.github/workflows/ci.yml

This was causing weirdness since we are 2 versions behind.

chore: update `karma-sauce-launcher` to 4
